#!/usr/bin/env bash

# Shared defaults for preference data, training, packaging, and evaluation.
# Callers may override every value through the corresponding environment variable.
PREFERENCE_BASE_MODEL_DEFAULT="Kwai-Klear/Klear-AgentForge-8B-SFT"
PREFERENCE_BASE_MODEL_REVISION_DEFAULT="0da97e45dbbd44278bd55b878170ec369d2934fb"
PREFERENCE_MAX_ROLLOUTS_DEFAULT=4
PREFERENCE_TRAIN_MAX_LENGTH_DEFAULT=32768
PREFERENCE_EVAL_CONTEXT_LENGTH_DEFAULT=32768
PREFERENCE_NUM_PROCESSES_DEFAULT=1
PREFERENCE_PER_DEVICE_BATCH_SIZE_DEFAULT=1
PREFERENCE_GRADIENT_ACCUMULATION_STEPS_DEFAULT=32
PREFERENCE_EPOCHS_DEFAULT=3
PREFERENCE_SAVE_STEPS_DEFAULT=100
PREFERENCE_DMPO_LEARNING_RATE_DEFAULT="1e-6"
PREFERENCE_DMPO_BETA_DEFAULT="0.1"
PREFERENCE_DMPO_GAMMA_DEFAULT="0.7"
PREFERENCE_DEPO_LEARNING_RATE_DEFAULT="2e-5"
PREFERENCE_DEPO_BETA_DEFAULT="0.2"
PREFERENCE_ALPHA_TOKENS_DEFAULT="2.0"
PREFERENCE_ALPHA_STEPS_DEFAULT="2.0"
PREFERENCE_TOKEN_METRIC_DEFAULT="total_tokens"
